// Objective-C API for talking to v2 Go package.
//   gobind -lang=objc v2
//
// File is generated by gobind. Do not edit.

#ifndef __V2_H__
#define __V2_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol V2PacketFlow;
@class V2PacketFlow;

@protocol V2PacketFlow <NSObject>
- (void)writePacket:(NSData* _Nullable)packet;
@end

FOUNDATION_EXPORT void V2InputPacket(NSData* _Nullable data);

FOUNDATION_EXPORT void V2StartV2Ray(id<V2PacketFlow> _Nullable packetFlow, NSData* _Nullable configBytes);

@class V2PacketFlow;

@interface V2PacketFlow : NSObject <goSeqRefInterface, V2PacketFlow> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)writePacket:(NSData* _Nullable)packet;
@end

#endif
