
// Objective-C API for talking to the following Go packages
//
//	v2orange
//
// File is generated by gomobile bind. Do not edit.
#ifndef __V2orange_FRAMEWORK_H__
#define __V2orange_FRAMEWORK_H__

#include "V2orange.objc.h"
#include "Universe.objc.h"

#endif
