// Objective-C API for talking to v2orange Go package.
//   gobind -lang=objc v2orange
//
// File is generated by gobind. Do not edit.

#ifndef __V2orange_H__
#define __V2orange_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol V2orangePacketFlow;
@class V2orangePacketFlow;

@protocol V2orangePacketFlow <NSObject>
- (void)writePacket:(NSData* _Nullable)packet;
@end

FOUNDATION_EXPORT void V2orangeInputPacket(NSData* _Nullable data);

FOUNDATION_EXPORT NSString* _Nonnull V2orangeLoadConfig(NSData* _Nullable configBytes);

FOUNDATION_EXPORT void V2orangePingRaw(NSString* _Nullable host);

FOUNDATION_EXPORT NSString* _Nonnull V2orangeProPing(NSString* _Nullable host, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL V2orangeStartV2Ray(id<V2orangePacketFlow> _Nullable packetFlow, NSData* _Nullable configBytes, NSError* _Nullable* _Nullable error);

@class V2orangePacketFlow;

@interface V2orangePacketFlow : NSObject <goSeqRefInterface, V2orangePacketFlow> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)writePacket:(NSData* _Nullable)packet;
@end

#endif
