
// Objective-C API for talking to the following Go packages
//
//	vDemoCore
//
// File is generated by gomobile bind. Do not edit.
#ifndef __VDemoCore_FRAMEWORK_H__
#define __VDemoCore_FRAMEWORK_H__

#include "VDemoCore.objc.h"
#include "Universe.objc.h"

#endif
