// Objective-C API for talking to vDemoCore Go package.
//   gobind -lang=objc vDemoCore
//
// File is generated by gobind. Do not edit.

#ifndef __VDemoCore_H__
#define __VDemoCore_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol VDemoCorePacketFlow;
@class VDemoCorePacketFlow;

@protocol VDemoCorePacketFlow <NSObject>
- (void)writePacket:(NSData* _Nullable)packet;
@end

FOUNDATION_EXPORT void VDemoCoreInputPacket(NSData* _Nullable data);

FOUNDATION_EXPORT void VDemoCoreStartV2Ray(id<VDemoCorePacketFlow> _Nullable packetFlow, NSData* _Nullable configBytes);

@class VDemoCorePacketFlow;

@interface VDemoCorePacketFlow : NSObject <goSeqRefInterface, VDemoCorePacketFlow> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)writePacket:(NSData* _Nullable)packet;
@end

#endif
