
// Objective-C API for talking to the following Go packages
//
//	v2
//
// File is generated by gomobile bind. Do not edit.
#ifndef __V2_FRAMEWORK_H__
#define __V2_FRAMEWORK_H__

#include "V2.objc.h"
#include "Universe.objc.h"

#endif
